### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by lemmy** [elastic/elasticsearch-formal-models#27]
Can you please clarify the license? We - https://github.com/tlaplus - might want to use your spec for (automated) performance testing. Thanks!

**Comment by DaveCTurner** [comment]
Good question. I will raise it with our legal team.

**Comment by ywelsch** [comment]
All cleared up. I've added a license file (Apache License 2.0) to the repository. Thanks for raising this @lemmy.

> We - https://github.com/tlaplus - might want to use your spec for (automated) performance testing

That sounds great. Would this be used to find performance regressions in TLC before release?

**Comment by lemmy** [comment]
Exactly, we use [it](https://tla.msr-inria.inria.fr/performance/) to detect performance regressions.
